[project]
name = "polids"
version = "2.0.0"
description = "Analysis of political data and output of it through apps."
authors = ["AndreCNF <andrecnf@gmail.com>"]
license = "MIT License"
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = [
    "docling>=2.28.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "marker-pdf>=0.2.17",
    "nbformat>=5.10.4",
    "plotly>=6.0.1",
]
