[tool.poetry]
name = "elections-analysis"
version = "0.1.0"
description = "Analysis of electoral programs and output of it through apps."
authors = ["AndreCNF <andrecnf@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
numpy = "^1.22.0"
PyYAML = "^6.0"
ipywidgets = "^7.6.5"
streamlit = "^1.3.1"
wordcloud = "^1.8.1"
spacy = "^3.2.1"
plotly = "^5.5.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
