[tool.poetry]
name = "elections-analysis"
version = "0.1.0"
description = "Analysis of electoral programs and output of it through apps."
authors = ["AndreCNF <andrecnf@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.8"
pandas = "^1.3.5"
numpy = "^1.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
