[project]
name = "polids"
version = "2.0.0"
description = "Analysis of political data and output of it through apps."
authors = ["AndreCNF <andrecnf@gmail.com>"]
license = "MIT License"
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = []
